function visualization_phase_index = ...
    visualize_sections_3d(data, geometry, sections, flow)
%VISUALIZE_SECTIONS_3D Vista 3D de malla, centerline y cortes.
%   Dibuja la superficie de la malla, la centerline y los cortes coloreados
%   por velocidad normal en la fase de mayor flujo medio, con vectores de
%   velocidad normal. Devuelve el indice de la fase visualizada.

    faces = data.faces;
    nodes = data.nodes;
    dataset_label = data.dataset_label;

    centerline_points_mm = geometry.centerline_points_mm;
    number_of_aortic_sections = geometry.number_of_aortic_sections;

    aortic_sections = sections.list;
    flow_rate_mL_per_s = flow.flow_rate_mL_per_s;

    average_flow_per_time_phase_mL_per_s = ...
        mean(flow_rate_mL_per_s, 1, 'omitnan');

    if all(~isfinite(average_flow_per_time_phase_mL_per_s))
        error('No fue posible calcular flujo valido en ningun corte.')
    elseif any(average_flow_per_time_phase_mL_per_s > 0)
        [~, visualization_phase_index] = ...
            max(average_flow_per_time_phase_mL_per_s);
    else
        [~, visualization_phase_index] = ...
            max(abs(average_flow_per_time_phase_mL_per_s));
        warning(['No se encontro una fase con flujo medio positivo. ', ...
            'Revise la orientacion de la centerline.'])
    end

    figure('Name', char(dataset_label + ": malla, 30 cortes y velocidad normal"))
    patch( ...
        'Faces', faces, ...
        'Vertices', nodes, ...
        'EdgeColor', 'none', ...
        'FaceColor', [0.75 0.75 0.75], ...
        'FaceAlpha', 0.15)
    hold on
    plot3( ...
        centerline_points_mm(:,1), ...
        centerline_points_mm(:,2), ...
        centerline_points_mm(:,3), ...
        'r', 'LineWidth', 1.5)

    velocity_vector_scale_mm_per_mps = 8;

    for section_index = 1:number_of_aortic_sections
        section_vertices_mm = aortic_sections(section_index).vertices_mm;
        section_faces = aortic_sections(section_index).faces;

        if isempty(section_vertices_mm)
            continue
        end

        section_normal_velocity_mps = aortic_sections(section_index). ...
            normal_velocity_mps(:, visualization_phase_index);
        section_normal_vector = aortic_sections(section_index).normal_vector;

        patch( ...
            'Faces', section_faces, ...
            'Vertices', section_vertices_mm, ...
            'FaceVertexCData', section_normal_velocity_mps, ...
            'FaceColor', 'interp', ...
            'EdgeColor', 'none', ...
            'FaceAlpha', 0.85)

        quiver_step = max(1, ceil(size(section_vertices_mm,1)/100));
        quiver_vertex_indices = 1:quiver_step:size(section_vertices_mm,1);
        quiver_velocity_values_mps = ...
            section_normal_velocity_mps(quiver_vertex_indices);
        valid_quiver_mask = isfinite(quiver_velocity_values_mps);

        quiver_vertex_indices = quiver_vertex_indices(valid_quiver_mask);
        quiver_velocity_values_mps = ...
            quiver_velocity_values_mps(valid_quiver_mask);

        quiver3( ...
            section_vertices_mm(quiver_vertex_indices,1), ...
            section_vertices_mm(quiver_vertex_indices,2), ...
            section_vertices_mm(quiver_vertex_indices,3), ...
            section_normal_vector(1) * ...
                quiver_velocity_values_mps * velocity_vector_scale_mm_per_mps, ...
            section_normal_vector(2) * ...
                quiver_velocity_values_mps * velocity_vector_scale_mm_per_mps, ...
            section_normal_vector(3) * ...
                quiver_velocity_values_mps * velocity_vector_scale_mm_per_mps, ...
            0, 'k', 'LineWidth', 0.6)
    end

    axis equal
    grid on
    view(3)
    xlabel('X [mm]')
    ylabel('Y [mm]')
    zlabel('Z [mm]')
    title(sprintf( ...
        '30 cortes qmeshcut y velocidad normal | fase %d', ...
        visualization_phase_index))
    colorbar
    colormap turbo
    hold off
end
