function FlowSummary = summarize_section_flow(geometry, flow, sections)
%SUMMARIZE_SECTION_FLOW Tabla resumen de area y flujo por corte.
%   Calcula el peak y la media del flujo de cada corte y arma la tabla
%   FlowSummary (area de Area.mat vs geometrica, su razon, origen del area y
%   flujos). La muestra por consola y la devuelve.

    number_of_aortic_sections = geometry.number_of_aortic_sections;
    section_arc_positions_m = geometry.section_arc_positions_m;
    laplace_cut_levels = geometry.laplace_cut_levels;

    flow_rate_mL_per_s = flow.flow_rate_mL_per_s;

    cross_section_area_m2 = sections.cross_section_area_m2;
    geometric_area_m2 = sections.geometric_area_m2;
    area_source = sections.area_source;

    peak_flow_per_section_mL_per_s = nan(number_of_aortic_sections, 1);
    mean_flow_per_section_mL_per_s = nan(number_of_aortic_sections, 1);

    for section_index = 1:number_of_aortic_sections
        section_flow_curve_mL_per_s = flow_rate_mL_per_s(section_index,:);
        section_flow_curve_mL_per_s = ...
            section_flow_curve_mL_per_s(isfinite(section_flow_curve_mL_per_s));

        if ~isempty(section_flow_curve_mL_per_s)
            peak_flow_per_section_mL_per_s(section_index) = ...
                max(section_flow_curve_mL_per_s);
            mean_flow_per_section_mL_per_s(section_index) = ...
                mean(section_flow_curve_mL_per_s);
        end
    end

    FlowSummary = table( ...
        (1:number_of_aortic_sections)', ...
        section_arc_positions_m(:), ...
        laplace_cut_levels(:), ...
        cross_section_area_m2, ...
        cross_section_area_m2*1e6, ...
        geometric_area_m2, ...
        geometric_area_m2*1e6, ...
        cross_section_area_m2 ./ geometric_area_m2, ...
        area_source, ...
        peak_flow_per_section_mL_per_s, ...
        mean_flow_per_section_mL_per_s, ...
        'VariableNames', { ...
            'Plane', ...
            's_m', ...
            'LaplaceLevel', ...
            'AreaMatUsed_m2', ...
            'AreaMatUsed_mm2', ...
            'GeometricArea_m2', ...
            'GeometricArea_mm2', ...
            'AreaMat_to_Geometric_Ratio', ...
            'AreaSource', ...
            'PeakFlow_mLs', ...
            'MeanFlow_mLs'});

    disp(FlowSummary)
end
